#!/bin/sh

# Get list of staged files
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

# Exit if no files are staged
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0